%resort(nome, preçomedio, [concelho,zona]), [], estrelas, avaliaçaomedia, interno[], externo[])

%Ruben
resort("Douro Cister Hotel Resort", 358, ['Ucanha', 'Norte', 6], [portuguesa], 4, 8.5, ['animais admitidos', 'atividades desportivas', internet, estacionamento, piscina_interior, 'Spa e centro de bem-estar', 'Centro Fitness'], [museu, teatro, catedral, mosteiro]).
resort("Prazer da Natureza Resort & Spa", 178, ['Caminha', 'Norte', 6], [europeia], 4, 8.6, ['atividades desportivas', internet, estacionamento, piscina, piscina_interior, 'Spa e centro de bem-estar', 'Centro Fitness'], [rio, montanha, mar, lago, praia]).
resort("Hotel Parque do Rio", 150, ['Esposende', 'Norte', 6], [portuguesa], 3, 7.5, ['atividades desportivas', internet, estacionamento, piscina], [rio, mar, montanha, praia]).
resort("Vale de Campos", 110, ['Penafiel', 'Norte', 6], [portuguesa], -, 8.5, ['animais admitidos', estacionamento, internet, 'Spa e centro de bem-estar', 'Centro Fitness'], [museu]).
resort("Bagos do Vilar", 150, ['Cadaval', 'Centro', 5], [portuguesa], -, 8.8, ['Spa e centro de bem-estar', piscina, terraco, jardim, internet, estacionamento, 'animais admitidos'], [jardim, museu, parque, montanha]).
resort("Dolce CampoReal Lisboa", 255, ['Turcifal', 'Centro', 5], [italiana, mediterranica, portuguesa, espanhola, 'local', internacional, "latino-americana"], 5, 8.6, [piscina_interior, piscina, 'Spa e centro de bem-estar', 'Centro Fitness', 'atividades desportivas', internet, estacionamento, 'animais admitidos'], [montanha]).
resort("Aqua Village, Health Resort", 437, ['Oliveira do Hospital', 'Centro', 5], [portuguesa], 5, 9.2, ['atividades desportivas', 'Spa e centro de bem-estar', 'Centro Fitness', biblioteca, piscina, piscina_interior, internet, estacionamento], [museu, lago, montanha]).
resort("The Beachfront - Praia D'EL Reu Golf & Beach Resort", 350, ['Casal da Lagoa Seca', 'Centro', 5], [portuguesa, marisco, 'local'], 5, 8.6, ['atividades desportivas', piscina, 'Centro Fitness', internet, estacionamento, 'animais admitidos'], ['campo de golfe', castelo, parque, jardim, terma, museu, praia]).
resort("Ohai Nazaré Outdoor Resort", 148, ['Nazaré','Centro', 5], [portuguesa, internacional], 3, 8.0, [estacionamento, piscina, 'animais admitidos', 'atividades desportivas', internet, 'Spa e centro de bem-estar', 'Centro Fitness'], [igreja, miradouro, castelo, mosteiro, forte, parque, praia, mar]).
resort("Bakubaki Eco Surg Resort", 174, ['Ferrel', 'Centro', 5], [italiana, mediterranica, portuguesa], 4, 8.3, ['Spa e centro de bem-estar', 'atividades desportivas', internet, estacionamento], [forte, praia, 'campo de golfe', parque, museu, terma, jardim]).
resort("West Cliffs Golf Villas", 374, ['Casal da Lagoa Seca', 'Centro', 5], [steakhouse, portuguesa], -, 9.0, ['atividades desportivas', internet, estacionamento, piscina], ['campo de golfe', castelo, praia, mar, parque, jardim, terma, museu]).
resort("L'AND Vineyards", 633, ['Montemor-o-Novo', 'Alentejo', 2], [portuguesa], 5, 8.8, ['atividades desportivas', internet, estacionamento, piscina, piscina_interior, 'Spa e centro de bem-estar'], []).
resort("Herdade da Caniceira", 380, ['Ervedal', 'Alentejo', 2], [portuguesa], -, 9.0, ['atividades desportivas', internet, estacionamento, piscina], [lago]).
resort("Pestana Troia Eco-Resort & Residences", 300, ['Tróia', 'Alentejo', 2], [portuguesa, europeia, pizza], 4, 8.1, ['animais admitidos', 'atividades desportivas', internet, estacionamento, piscina, piscina_interior, 'Spa e centro de bem-estar', 'Centro Fitness'], [mar, rio, montanha, praia, 'campo de golfe', parque, museu]).
resort("Pedras do Mar Resort & Spa", 260, ['Fenais da Luz', 'Açores', 3], [portuguesa, internacional], 5, 8.8, ['atividades desportivas', internet, estacionamento, piscina_interior, piscina, 'Spa e centro de bem-estar', 'Centro Fitness'], ['campo de golfe', igreja, lago, santuario, ponte]).
resort("Quinta das Rosas Villas", 160, ['Ribeira Grande', 'Açores', 3], [portuguesa], -, 9.4, ['atividades desportivas', internet, estacionamento, piscina], [ponte, igreja, lago, santuario, ermida, fumarolas, mar, montanha, 'campo de golfe']).
resort("Aldeia das Adegas", 200, ['São Roque do Pico', 'Açores', 3], [portuguesa], 4, 8.9, [internet, estacionamento], []).
resort("Aldeia da Fonte Hotel", 200, ['Lajes do Pico', 'Açores', 3], [portuguesa, internacional], 4, 8.4, ['animais admitidos', 'atividades desportivas', internet, estacionamento, piscina, 'Centro Fitness'], [mar, praia]).
resort("Caparica Azores Ecolodge", 345, ['Biscoitos', 'Açores', 3], [portuguesa], -, 9.2, ['atividades desportivas', internet, estacionamento, piscina], [mar, montanha, praia]).
resort("Saccharum - Resort & Spa - Savoy Signature", 308, ['Calheta', 'Madeira', 4], [internacional], 5, 9.2, ['atividades desportivas', internet, estacionamento, piscina_interior, piscina, 'Spa e centro de bem-estar', 'Centro Fitness'], [gruta, piscina, mar, montanha, praia]).
resort("Escarpa - The Madeira Hideaway", 170, ['Ponta do Sol', 'Madeira', 4], [mediterranica, portuguesa, marisco, 'local'], -, 9.7, [internet, estacionamento, piscina], [gruta, miradouro, casino, parque, marina, praia]).
resort("Hotel Apartamento Cais da Oliveira", 205, ['Caniço', 'Madeira', 4], [portuguesa], 4, 8.2, ['atividades desportivas', internet, estacionamento, piscina_interior, piscina, 'Spa e centro de bem-estar', 'Centro Fitness'], [praia, quinta, 'campo de golfe', museu, casino, jardim, marina, miradouro]).
resort("Pestana Colombos Premium Clube - All inclusive", 745, ['Porto Santo', 'Madeira', 4], [portuguesa], 5, 8.6, ['atividades desportivas', internet, estacionamento, piscina_interior, piscina, 'Spa e centro de bem-estar', 'Centro Fitness'], [quinta, praia]).

%Anabela
resort("Alfagar_Village", 129, ['Albufeira', 'Algarve', 1],[portuguesa, internacional], 3, 8.75, ['piscina interior', piscina, terraco, jardim, 'centro fitness', 'entretenimento noturno', karaoke, 'tenis de mesa', bilhar, 'parque infantil', 'sala de jogos', 'campo de golfe', 'campo de tenis', 'spa e centro de bem estar', 'estacionamento gratuito', 'transfer aeroporto', internet, babysitting], [praia, snorkelling, equitaçao, pesca]).
resort("Grande Real Santa Eulalia Resort & Hotel Spa", 198, ['Albufeira', 'Algarve', 1], [europeia,'local'] , 5, 8.8, [piscina, terraco, jardim, discoteca, 'equipa de entertenimento', 'parque infantil', 'centro fitness', 'campo de golfe', 'campo de tenis', 'spa e centro de bem estar', estacionamento, 'servico de transporte', internet], [praia]).
resort("Salgados Dunas Suites", 192,  ['Albufeira', 'Algarve', 1], [mediterrânica, portuguesa, 'local'], 5, 8.45, [piscina, terraco, jardim, 'transmissao de eventos derportivos', 'musica ao vivo', 'entretenimento noturno', 'clube infantil', 'equipa de entretenimento', bilhar, 'sala de jogos','spa e centro de bem estar','centro fitness', 'campo de golfe', estacionamento,  'transfer aeroporto', internet, babysitting], [praia,'campo de tenis', pesca, snorkelling, equitaçao, mergulho, caminhadas, canoagem, windsurf,'excursoes de bicicleta', 'excursoes a pe']).
resort("PortoBay Falesia", 255,  ['Albufeira', 'Algarve', 1], [internacional, mediterrânica], 4, 9.0, [piscina, terraco, jardim, 'tenis de mesa', 'sala de jogos', 'parque infantil', 'spa e centro de bem estar','centro fitness', 'campo de tenis', estacionamento,  'transfer aeroporto', internet, babysitting], [praia, caminhadas]).
resort("Salgados Palm Village Apartments & Suites", 434,  ['Albufeira', 'Algarve', 1], [italiana, internacional, portuguesa], 4, 8.3, [piscina, terraco, jardim, 'musica ao vivo', 'entretenimento noturno', 'noites de cinema', 'stand-up comedy','clube infantil', 'equipa de entretenimento', minigolfe, equitacao, setas, karaoke, 'tenis de mesa', bilhar, 'sala de jogos', 'parque infantil', 'spa e centro de bem estar','centro fitness', 'campo de golfe', 'campo de tenis', estacionamento,  'transfer aeroporto', internet, babysitting, 'Equipamento para jogos infantis no exterior', 'area de jogos interior', 'jogos de tabuleiro'], [praia, 'parque aquatico', 'excursoes de bicicleta', mergulho, caminhadas]).
resort("Pine Cliffs Hotel, a Luxury Collection Resort", 584,  ['Albufeira', 'Algarve', 1], [europeia, portuguesa, asiatica, saudavel], 5, 8.85, [piscina, terraco, jardim, 'aulas de culinária', 'clube infantil', minigolfe, 'tenis de mesa', 'parque infantil', 'campo de golfe', 'campo de tenis', 'spa e centro de bem estar','centro fitness', estacionamento,  'transfer aeroporto', internet, 'equipamento para jogos infantis no exterior', babysitting], [praia, 'excursoes de bicicleta', ciclismo]).
resort("Salgados Palace", 408,  ['Albufeira', 'Algarve', 1], [mediterrânica, internacional, portuguesa], 5, 8.45, [piscina, terraco, jardim, 'transmissao de eventos desportivos', 'musica ao vivo', 'entretenimento noturno', 'clube infantil', 'discoteca', 'equipa de entretenimento', mingolfe, bilhar, 'parque infantil', 'campo de golfe','spa e centro de bem estar','centro fitness', estacionamento,  'transfer aeroporto', internet, babysitting], [praia, 'parque aquatico', snorkelling, equitacao, mergulho, caminhadas, canoagem, windsurf, pesca, 'campo de tenis']).
resort("VidaMar Resort Hotel Algarve", 173,  ['Albufeira', 'Algarve', 1], [internacional, italiana, asiatica, mediterrânica], 5, 8.5, ['piscina interior', piscina, terraco, jardim, 'transmissao de eventos desportivos', 'musica ao vivo', 'jantares temmaticos', 'entretenimento noturno', 'clube infantil', 'equipa de entretenimento', bilhar, 'sala de jogos','spa e centro de bem estar','centro fitness', 'campo de golfe', internet, babysitting, 'Equipamento para jogos infantis no exterior', 'area de jogos interior'], [praia, 'excursoes de bicicleta', 'excursoes a pe', snorkelling, equitacao, mergulho, ciclismo, caminhadas, canoagem, windsurf, pesca, 'campo de tenis', 'parque aquatico']).
resort("Vila Gale Cerro Alagoa", 208, ['Albufeira', 'Algarve', 1], [internacional], 4, 8.15, ['piscina interior', piscina, jardim, 'clube infantil', bilhar, 'sala de jogos', 'parque infantil','spa e centro de bem estar','centro fitness', internet], [praia]).
resort("AP Adriana Beach Resort", 149, ['Albufeira', 'Algarve', 1], [portuguesa, internacional], 4, 8.2, [piscina, terraco, jardim, 'bingo', 'aerobica', 'transmissao de eventos derportivos', 'musica ao vivo', 'jantares tematicos', 'entretenimento noturno', 'clube infantil', 'equipa de entretenimento', bilhar, 'sala de jogos', minigolfe, equitacao, setas, 'tenis de mesa', 'parque infantil', 'campo de tenis', 'spa e centro de bem estar','centro fitness', 'campo de golfe',  'transfer aeroporto', internet, babysitting, 'jogos de tabuleiro'], [praia, caminhadas, passeio, 'excursoes a pe', 'excursoes de bicicleta', ciclismo]).
resort("Jupiter Albufeira Hotel - Family & Fun", 205, ['Albufeira', 'Algarve', 1], [italiana, mediterrânica, portuguesa, 'local'], 5, 8.75, ['piscina interior', piscina, terraco, jardim, 'transmissao de eventos derportivos', 'musica ao vivo', 'happy hour', 'jantares tematicos', 'parque aquatico', 'entretenimento noturno', 'clube infantil', 'equipa de entretenimento', bilhar, setas, 'tenis de mesa','sala de jogos', 'campo de tenis', 'parque infantil', 'spa e centro de bem estar','centro fitness', 'campo de golfe',  'transfer aeroporto', internet, babysitting, 'equipamento para jogos infantis no exterior', 'area de jogos interior', 'jogos de tabuleiro'], [praia, 'excursoes de bicicleta', ciclismo, caminhadas]).
resort("Eden Resort", 225, ['Albufeira', 'Algarve', 1], [internacional], 4, 8.75,[piscina, terraco, jardim, 'transmissao de eventos derportivos', 'musica ao vivo', 'clube infantil', 'parque infantil','spa e centro de bem estar', 'campo de golfe', 'campo de tenis', estacionamento, internet, babysitting, 'equipamento para jogos infantis no exterior'], [praia, 'parque aquatico', ciclismo]).
resort("Alfagar Aparthotel", 169, ['Albufeira', 'Algarve', 1], [internacional], 4, 8.9, ['piscina interior',piscina,  'transmissao de eventos derportivos', 'musica ao vivo', 'entretenimento noturno', 'clube infantil', 'equipa de entretenimento', bilhar, 'sala de jogos','spa e centro de bem estar','centro fitness', 'campo de golfe', estacionamento, internet, babysitting, 'area de jogos interior', 'entretenimento noturno', 'karaoke', 'parque infantil'], [praia]).
resort("Clube Albufeira Garden Village", 72, ['Albufeira', 'Algarve', 1], [portuguesa, internacional, 'local'], 4, 8.0, [piscina, 'clube infantil', minigolfe, bilhar, 'parque infantil', estacionamento, internet,'equipamento para jogos infantis no exterior'], [praia, 'parque aquatico', 'excursoes de bicicleta']).
resort("Balaia Golf Village", 127, ['Albufeira', 'Algarve', 1], [portuguesa], 4, 8.3, [piscina, jardim, terraco, 'aulas de culinaria', 'clube infantil', bowling, 'tenis de mesa', bilhar, 'parque infantil', 'campo de golfe', 'campo de tenis', estacionamento, internet, 'equipamento para jogos infantis no exterior'], [praia, 'parque aquatico', 'excursoes de bicicleta', ciclismo]).
resort("Rocha Brava Village Resort", 202, ['Albufeira', 'Algarve', 1], [portuguesa, internacional], 5, 8.35, [piscina, jardim, terraco, aerobica, minigolfe, 'tenis de mesa', 'parque infantil', 'sala de jogos', 'campo de golfe', 'campo de tenis', estacionamento, internet, 'centro fitness', babysitting],[praia, 'parque aquatico', snorkelling, mergulho, equitacao, pesca, caminhadas, ciclismo]).
resort("Vila Balaia - Luxury Villas Resort", 869, ['Albufeira', 'Algarve', 1], [mediterrânica, portuguesa, internacional], 5, 9.6, [piscina, jardim, terraco, patio, 'parque infantil',setas, 'tenis de mesa', bilhar, 'campo de tenis', 'campo golfe', estacionamento, internet,babysitting], [praia, 'excursoes de bicileta', equitacao, ciclismo, caminhadas]).

%Mariana
resort("Pine Hills Vilamoura", 302, ['Vilamoura', 'Algarve', 1], [portuguesa], -, 9.2, [piscina, internet, estacionamento, 'Campo de golf', 'Chaleira no quarto', 'Spa e centro de bem-estar'], [marina, praia, mergulho, 'equitação', windsurf, 'parque aquático', pesca]).
resort("Pestana Vila Sol Golf & Resort Hotel", 268, ['Vilamoura', 'Algarve', 1], [mediterranica], 5, 8.1, [piscina, estacionamento, internet, babysitting, 'atividades desportivas'], [marina, praia , 'Parque aquático']).
resort("Hilton Vilamoura", 412, ['Vilamoura', 'Algarve', 1], [mediterranica, portuguesa], 5, 8.4, ['praia privada', piscina, 'Transfer aeroporto', estacionamento, 'Salão de beleza', internet, 'Bowling', 'Spa e centro de bem-estar'], ['Ruínas romanas', praia, 'campo de golfe', marina]).
resort("Crowne Plaza Vilamoura - Algarve, an IHG Hotel", 665, ['Vilamoure', 'Algarve', 1], [mediterranica, portuguesa, europeia, churrasco, marisco, 'local', internacional, steakhouse], 5, 8.8, [piscina, 'Transfer aeroporto', estacionamento, 'Spa e centro de bem-estar', babysitting, internet, 'campo de ténis'], [marina, 'campo de golfe', praia, 'Ruínas romanas']).
resort("Four Seasons Vilamoura", 465, ['Vilamoura', 'Algarve', 1], [brasileira, inglesa, italiana, portuguesa, pizza, churrasco, 'local', internacional, europeia], 4, 8.2, [piscina, 'Transfer aeroporto', estacionamento, 'Spa e centro de bem-estar', babysitting, internet], ['campo de golfe', praia, marina]).
resort("Laguna Resort-Vilamoura", 306, ['Vilamoura' , 'Algarve', 1], [portuguesa], 4, 8.8, [piscina, internet, estacionamento], ['campo de golfe', marina, praia]).
resort("Dona Filipa Hotel", 998, ['Vale do Lobo', 'Algarve', 1], [portuguesa], 5, 7.9, ['Transfer aeroporto', 'praia privada', internet, estacionamento, babysitting, 'Minigolf', 'campo de ténis'], ['campo de golfe', praia]).
resort("Dunas Douradas Beach Club", 886, ['Vale do Lobo', 'Algarve', 1], [mediterranica, portuguesa, internacional], 5, 9.3, [piscina, 'Spa e centro de bem-estar', estacionamento, 'Transfer aeroporto', 'minimercado', 'campo de golfe'], [praia, marina, pesca, mergulho, 'campo de ténis', snorkelling]).
resort("Wyndham Grand Algarve", 706, ['Quinta do Lago', 'Algarve', 1], [internacional, portuguesa], 5, 8.5, [piscina, 'Spa e centro de bem-estar', internet, estacionamento, babysitting, 'Transfer aeroporto', 'Centro fitnesse'], [snorkelling, pesca, canoagem, 'campo de golfe', marina, praia]).
resort("Martinhal Quinta Family Resort", 616, ['Quinta do Lago', 'Algarve', 1], [portuguesa], 4, 8.8, [piscina, internet, estacionamento, 'Transfer aeroporto', 'Spa e centro de bem-estar', babysitting, 'Excrusões de bicicleta'], ['campo de golfe', praia, 'teatro de figuras']).
resort("Amendoeira Golf Resort", 187, ['Armação de Pêra', 'Algarve', 1], [portuguesa, internacional], 4, 8.7, [piscina, 'Transfer aeroporto', internet, babysitting], [praia, 'parque aquático', 'Capela Nossa Senhora da Rocha']).
resort("Vilalara Thalassa Resort", 1040, ['Armação de Pêra', 'Algarve', 1], [portuguesa], 5, 9.3, [piscina, 'Transfer aeroporto', babysitting, 'Spa e centro de bem-estar'], [praia, 'parque aquático', 'Capela Nossa Senhora da Rocha']).
resort("Pestana Viking Beach & SPA Resort", 190, ['Armação de Pêra', 'Algarve', 1], [portuguesa], 4, 9.2, [piscina, 'Transfer aeroporto', internet, estacionamento, babysitting, 'animais admitidos'], [canoagem, praia, mergulho, windsurf, snorkelling, 'Capela Nossa Senhora da Rocha']).
resort("Vale da Ribeira Residences", 189, ['Portimão', 'Algarve', 1], [portuguesa], -, 9.1, [piscina, 'Transfer aeroporto', internet, estacionamento, minimercado, babysitting], [praia, 'campo de golfe', windsurf, pesca, equitação, ciclismo]).
resort("Vale d'El Rei Hotel & Villa", 203, ['Carvoeiro', 'Algarve', 1], [mediterranica, portuguesa], 4, 8.6, [piscina, 'Transfer aeroporto', internet, estacionamento, bilhar, babysitting, 'Spa e centro de bem-estar'], [praia, pesca, snorkelling, mergulho, 'campo de golfe', equitação]).
resort("Vale d'Oliveiras Quinta Resort & SPA", 265, ['Carvoeiro','Algarve', 1], [portuguesa], 5, 8.9, [piscina, 'Transfer aeroporto', 'Serviço de quartos', 'Spa e centro de bem-estar', mergulho, aeróbica, bilhar, 'ténis de mesa'], [praia, 'campo de golfe', 'parque aquático', 'Museu de Portimão']).
resort("Rocha Brava Village Resort", 202, ['Carvoeiro','Algarve', 1], [portuguesa, internacional], 4, 8.5, [piscina, estacionamento, internet, babysitting, 'campo de ténis', 'Spa e centro de bem-estar', minigolfe, minimercado], [praia, equitação, pesca, 'campo de golfe', snorkelling]).
resort("Monte Santo Resort", 341, ['Carvoeiro','Algarve', 1], [portuguesa], 5, 8.6, [piscina, 'Transfer aeroporto', 'Spa e centro de bem-estar', babysitting], ['campo de golfe', praia, 'parque aquatico', equitação, mergulho, snorkelling, windsurf, canoagem]).
resort("Penina Hotel & Golf Resort", 322, ['Portimão', 'Algarve', 1], [internacional, italiana, mediterranica, portuguesa], 5, 8.1, [piscina, 'Transfer aeroporto', 'praia privada', internet, babysitting], ['campo de golfe', praia]).

